# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 5
    package-ecosystem: "composer"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "symfony/css-selector"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/framework-bundle"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/dotenv"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/form"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/google-mailer"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/mailer"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/proxy-manager-bridge"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/property-info"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/yaml"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/validator"
        versions: ["5.x", "6.x"]
#      - dependency-name: "symfony/phpunit-bridge"
#        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/browser-kit"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/web-profiler"
        versions: ["5.x", "6.x"]



  #
  # Tools dependecy track
  #
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/phpstan"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/psalm"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/ecs"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "tool dependency"


#  - commit-message:
#      include: "scope"
#      prefix: "github-actions"
#    directory: "/"
#    labels:
#      - "dependency"
#    open-pull-requests-limit: 1
#    package-ecosystem: "github-actions"
#    schedule:
#      interval: "weekly"
