# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 15
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "01:00"
      timezone: "Europe/Rome"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "dependency"
    groups:
      symfony_dev:
        applies-to: "version-updates"
        dependency-type: "development"
        patterns:
          - "symfony/stopwatch"
          - "symfony/browser-kit"
          - "symfony/debug-bundle"
          - "symfony/css-selector"
          - "symfony/phpunit-bridge"
          - "symfony/web-profiler-bundle"
        update-types:
          - "patch"
      symfony_prod:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "symfony/*"
        update-types:
          #- "minor"
          - "patch"
      doctrine:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "doctrine/*"
        update-types:
          #- "minor"
          - "patch"
      twig-extra:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "twig/extra-bundle"
          - "twig/*-extra"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "doctrine/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "ecotone/*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "knpuniversity/oauth2-client-bundle"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "twig/*-extra"
        update-types: ["version-update:semver-major"]



  #
  # Tools dependecy track
  #
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/phpstan"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/psalm"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/ecs"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "tool dependency"


  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/"
    labels:
      - "GHA dependency"
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
