doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        server_version: 'mariadb-10.3.29'
        driver: 'pdo_mysql'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        types:
            reservation_status: Booking\Adapter\Persistance\DoctrineType\ReservationStatusType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Booking:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/core/booking/src/Application/Domain/Model'
                prefix: 'Booking\Application\Domain\Model'
                alias: Booking
