sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        sample_rate: 1.0
        traces_sample_rate: 0.5
    tracing:
        enabled: true
        dbal: # DB queries
            enabled: true
        cache:
            enabled: true
        twig: # templating engine
            enabled: true

monolog:
    handlers:
        sentry:
            type: service
            id: Sentry\Monolog\Handler

services:
    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR

####### configuration reference #######
# https://docs.sentry.io/platforms/php/guides/symfony/config/


#sentry:
#    dsn: "https://examplePublicKey@o0.ingest.sentry.io/0"
#    register_error_listener: true
#    options:
#        attach_stacktrace: true
#        before_breadcrumb: "@sentry.callback.before_breadcrumb"
#        before_send: "@sentry.callback.before_send"
#        capture_silenced_errors: false
#        context_lines: 5
#        default_integrations: true
#        enable_compression: true
#        environment: "%kernel.environment%"
#        error_types: "E_ALL & ~E_NOTICE"
#        http_proxy: "10.0.0.12:3456"
#        in_app_exclude:
#            - "%kernel.cache_dir%"
#            - "%kernel.project_dir%/vendor"
#        integrations:
#            - "@sentry.integration.my_custom_integration"
#        logger: "php"
#        max_breadcrumbs: 50
#        max_value_length: 2048
#        prefixes:
#            - "/local_dir/"
#        project_root: "%kernel.project_dir%"
#        release: "abcde12345"
#        sample_rate: 1
#        send_attempts: 3
#        send_default_pii: true
#        server_name: "www.example.com"
#        tags:
#            tag1: "value1"
#            tag2: "value2"
#    listener_priorities:
#        request: 1
#        subrequest: 1
#        console: 1