version: '3.8'

services:
  app:
    build:
      context: .
      target: php_dev
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    volumes:
      - .:/app

  nginx:
    image: nginx:1.22-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mariadb:10.3.29
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'oberdan'
      MYSQL_USER: 'oberdan'
      MYSQL_PASSWORD: 'oberdan'

  mysql-test:
    image: mariadb:10.3.29
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'docker'
      MYSQL_DATABASE: 'symfony_test'
      MYSQL_USER: 'symfony'
      MYSQL_PASSWORD: 'docker'

#  phpmyadmin:
#    image: 'phpmyadmin/phpmyadmin'
#    ports:
#      - '81:80'
#    links:
#      - db:mysql
#    environment:
#      MYSQL_USERNAME: root
#      MYSQL_ROOT_PASSWORD: docker
#      PMA_HOST: mysql

  encore:
    image: node:16-alpine
    environment:
      USER: node
    working_dir: /app
    volumes:
      - .:/app
    command: ["yarn", "encore", "dev", "--watch" ]