version: '3.8'

services:
  app:
    image: webdevops/php-nginx-dev:7.4
    user: application
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      XDEBUG_MODE: coverage
      PHP_MEMORY_LIMIT: 128M
    volumes:
      - .:/app
      #- ~/.ssh/id_rsa.pub:/home/application/.ssh/authorized_keys:ro
    ports:
      - "127.0.0.222:8888:80"
      - "80:80"
    depends_on:
      - mysql

  mysql:
    #image: mysql:5.7
    image: mariadb:10.3.29
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'oberdan'
      MYSQL_USER: 'oberdan'
      MYSQL_PASSWORD: 'oberdan'
    #volumes:
      #- ./build/mysql:/var/lib/mysql
#
#  phpmyadmin:
#    image: 'phpmyadmin/phpmyadmin'
#    ports:
#      - '81:80'
#    links:
#      - db:mysql
#    environment:
#      MYSQL_USERNAME: root
#      MYSQL_ROOT_PASSWORD: docker
#      PMA_HOST: mysql

  encore:
    image: node:12-alpine
    container_name: encore
    environment:
      USER: node
    working_dir: /app
    volumes:
      - .:/app
    command: ["yarn", "encore", "dev", "--watch" ]