<?php

declare(strict_types=1);

namespace Booking\Application\Domain\Model\ConfirmationStatus;

use DateTimeImmutable;

/**
 * Generated by prolic/fpp - do not edit !!!
 * @codeCoverageIgnore
 */
final class ConfirmationStatus
{
    /**
     * @var int  numero di giorni prima di essere considerato scaduto
     */
    private const DEFAULT_EXPIRATION_TIME = 7;

    /**
     * @var int numero di giorni da sommare al default expiration time
     */
    private const EXTENDED_EXPIRATION_TIME = 7;

    private DateTimeImmutable $confirmedAt;

    private extensionTime $extensionTime;

    private expired $expired;

    public function __construct(DateTimeImmutable $confirmedAt, extensionTime $extensionTime, expired $expired)
    {
        $this->confirmedAt = $confirmedAt;
        $this->extensionTime = $extensionTime;
        $this->expired = $expired;
    }

    public static function create(DateTimeImmutable $confirmedAt): self
    {
        return new self(
            $confirmedAt,
            new extensionTime(false),
            new expired(false)
        );
    }

    public function isExpired(): bool
    {
        $today = new \DateTimeImmutable("now", new \DateTimeZone('Europe/Rome'));

        $expirationDays = $this->extensionTime()->value() === true ? self::DEFAULT_EXPIRATION_TIME + self::EXTENDED_EXPIRATION_TIME : self::DEFAULT_EXPIRATION_TIME;

        $interval = $this->confirmedAt()->diff($today);

        if ($interval->days >= $expirationDays) {
            return true;
        } else {
            return false;
        }
    }

    public function confirmedAt(): DateTimeImmutable
    {
        return $this->confirmedAt;
    }

    public function withConfirmedAt(DateTimeImmutable $confirmedAt): self
    {
        return new self(
            $confirmedAt,
            $this->extensionTime,
            $this->expired
        );
    }

    public function extensionTime(): extensionTime
    {
        return $this->extensionTime;
    }

    public function withExtensionTime(extensionTime $extensionTime): self
    {
        return new self(
            $this->confirmedAt,
            $extensionTime,
            $this->expired
        );
    }

    public function expired(): expired
    {
        return $this->expired;
    }

    public function withExpired(expired $expired): self
    {
        return new self(
            $this->confirmedAt,
            $this->extensionTime,
            $expired
        );
    }

    public static function fromArray(array $data): self
    {
        //if (! isset($data['confirmedAt']) || ! DateTimeImmutable::createFromFormat('Y-m-d\TH:i:s.uP', $data['confirmedAt'], new \DateTimeZone('UTC'))
        if (! isset($data['confirmedAt']) || ! DateTimeImmutable::createFromFormat('Y-m-d\TH:i:s.uP', $data['confirmedAt'], new \DateTimeZone('Europe/Rome'))
        ) {
            throw new \InvalidArgumentException('Error on "confirmedAt", datetime string expected');
        }

        if (! isset($data['extensionTime']) || ! \is_bool($data['extensionTime'])) {
            throw new \InvalidArgumentException('Error on "extensionTime", bool expected');
        }

        if (! isset($data['expired']) || ! \is_bool($data['expired'])) {
            throw new \InvalidArgumentException('Error on "expired", bool expected');
        }

        return new self(
            (function () use ($data) {
                //$_x = DateTimeImmutable::createFromFormat('Y-m-d\TH:i:s.uP', $data['confirmedAt'], new \DateTimeZone('UTC'));
                $_x = DateTimeImmutable::createFromFormat('Y-m-d\TH:i:s.uP', $data['confirmedAt'], new \DateTimeZone('Europe/Rome'));

                if (false === $_x) {
                    throw new \UnexpectedValueException('Expected a date time string');
                }

                return $_x;
            })(),
            new extensionTime($data['extensionTime']),
            new expired($data['expired']),
        );
    }

    public function toArray(): array
    {
        return [
            'confirmedAt' => $this->confirmedAt->format('Y-m-d\TH:i:s.uP'),
            'extensionTime' => $this->extensionTime->value(),
            'expired' => $this->expired->value(),
        ];
    }

    public function equals(?ConfirmationStatus $other): bool
    {
        if (! $other instanceof self) {
            return false;
        }

        if (! ($this->confirmedAt === $other->confirmedAt)) {
            return false;
        }

        if (! $this->extensionTime->equals($other->extensionTime)) {
            return false;
        }

        if (! $this->expired->equals($other->expired)) {
            return false;
        }

        return true;
    }
}
