# See full configuration: https://github.com/zenstruck/foundry#full-default-bundle-configuration
zenstruck_foundry:
    # Whether to auto-refresh proxies by default (https://github.com/zenstruck/foundry#auto-refresh)
    auto_refresh_proxies: true

    faker:
        locale: it_IT # set the locale
        # or
        #service: my_faker # use your own instance of Faker\Generator for complete control
