# See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
zenstruck_foundry:
    # Whether to auto-refresh proxies by default (https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#auto-refresh)
    auto_refresh_proxies: true

    faker:
        locale: it_IT # set the locale
        # or
        #service: my_faker # use your own instance of Faker\Generator for complete control
