version: '3.8'

services:
  php:
    build:
      context: ../buildDocker/php
      shm_size: '512m'
    container_name: app
    volumes:
      - ./:/var/www/html/symfony
    depends_on:
      - mysql

  web:
    build: ../buildDocker/nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html/symfony
    depends_on:
      - php

  mysql:
    image: mariadb:10.3.29
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'docker'
      MYSQL_DATABASE: 'symfony'
      MYSQL_USER: 'symfony'
      MYSQL_PASSWORD: 'docker'
#    volumes:
#      - ./build/mysql:/var/lib/mysql

  mysql-test:
    image: mariadb:10.3.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'docker'
      MYSQL_DATABASE: 'symfony_test'
      MYSQL_USER: 'symfony'
      MYSQL_PASSWORD: 'docker'


#  phpmyadmin:
#    image: 'phpmyadmin/phpmyadmin'
#    ports:
#      - '81:80'
#    links:
#      - db:mysql
#    environment:
#      MYSQL_USERNAME: root
#      MYSQL_ROOT_PASSWORD: docker
#      PMA_HOST: mysql

  encore:
    build:
      context: ../buildDocker/node
    #image: node:12-alpine
    container_name: encore
    environment:
      USER: node
      PYTHON: python3
    working_dir: /app
    volumes:
      - .:/app
    command: ["yarn", "encore", "dev", "--watch" ]