#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home_oberdan:
  path: /
  controller: Booking\Adapter\HttpDriver\HomeController

reservation_oberdan:
  path: /reservation
  controller: Booking\Adapter\HttpDriver\ReservationController