#
# Backoffice routes redirect to dashboard controller
#
admin_home:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'backoffice_dashboard'
    permanent: true