#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home_oberdan:
  path: /
  controller: Booking\Adapter\HttpDriver\HomeController

reservation:
  path: /reservation
  controller: Booking\Adapter\HttpDriver\ReservationController

reservation_adozioni:
  path: /reservation/adozioni
  controller: Booking\Adapter\HttpDriver\AdozioniController

reservation_result:
  path: /esito
  controller: Booking\Adapter\HttpDriver\ReservationResultsController

#
# Backoffice routes
#
admin_home:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'backoffice_dashboard'
    permanent: true