#reservation_adozioni:
#  path: /reservation/adozioni
#  controller: Booking\Adapter\HttpDriver\AdozioniReservationController

reservation_result:
  path: /esito
  controller: Booking\Adapter\HttpDriver\ReservationResultsController

#
# Backoffice routes
#
admin_home:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'backoffice_dashboard'
    permanent: true