services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    #limiter.reservation_forms:
#    Symfony\Component\RateLimiter\RateLimiterFactory:
#        alias: limiter.reservation_forms
#        abstract: true
#        public: true
