# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    #mailer.global.sender: 'prenotazioni@8viadeilibrai.it'
    #mailer.global.sender: 'info@oberdan8.it'
    mailer.global.sender: 'info@8viadeilibrai.it'
    mailer.global.sender.as: 'Oberdan 8'

    booking.mailer.backoffice.retriever.address: 'info@oberdan8.it'
    booking.mailer.backoffice.retriever.name: 'Gestione prenotazioni'

    booking.adozioni_directory: '%kernel.project_dir%/public/uploads/reservation'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        # setup special, global autowiring rules
        bind:
            #$markdownLogger: '@monolog.logger.markdown'
            $isDebug: '%kernel.debug%'
            #$uploadsFilesystem: '@oneup_flysystem.uploads_filesystem_filesystem'
            #$uploadedAssetsBaseUrl: '%uploads_base_url%'
            string $publicDir: '%kernel.project_dir%/public'


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Form/Model/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']


    #
    #   BOOKING BOUNDED CONTEXT
    #
    Booking\:
        resource: '../core/booking/src/'
        exclude:
            - '../core/booking/src/Application/Domain/Model'
            - '../core/booking/src/Infrastructure/Framework/templates'
            - '../core/booking/src/Adapter/Web/Free/Form/Dto'
            - '../core/booking/src/Adapter/Web/Admin/Form/Dto'
            - '../core/booking/src/Adapter/Web/Admin/Form/Model'

    Booking\Adapter\Web\Free\:
        resource: '../core/booking/src/Adapter/Web/Free/'
        exclude:
            - '../core/booking/src/Adapter/Web/Free/Form'
        tags: [ 'controller.service_arguments' ]

    Booking\Adapter\Web\Admin\:
        resource: '../core/booking/src/Adapter/Web/Admin/'
        exclude:
            - '../core/booking/src/Adapter/Web/Admin/Form'
        tags: [ 'controller.service_arguments' ]

    Booking\Infrastructure\Framework\:
        resource: '../core/booking/src/Infrastructure/Framework/'
        exclude:
            - '../core/booking/src/Infrastructure/Framework/templates'

    Booking\Infrastructure\Uploader\AdozioniUploaderInterface: '@Booking\Infrastructure\Uploader\AdozioniUploader'
    Booking\Infrastructure\Uploader\AdozioniUploader:
        arguments:
            - '%booking.adozioni_directory%'


    Booking\Infrastructure\BookingConfiguration:
        arguments:
            - '%mailer.global.sender%'
            - '%mailer.global.sender.as%'
            - '%booking.mailer.backoffice.retriever.address%'
            - '%booking.mailer.backoffice.retriever.name%'

    Booking\Infrastructure\BookingEmailSender:
        factory: [ '@Booking\Infrastructure\BookingConfiguration', 'emailSender' ]

    Booking\Infrastructure\BackofficeEmailRetriever:
        factory: [ '@Booking\Infrastructure\BookingConfiguration', 'backofficeEmailRetriever' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Booking\Application\Domain\Model\ReservationRepositoryInterface:
        class: Booking\Adapter\Persistence\ReservationRepository

    # TODO added for test purpose  remove...
    Booking\Adapter\Persistence\ReservationRepository:
        public: true


    App\Repository\BackofficeUserRepository:
        public: true